# Generated by Django 3.0.5 on 2020-05-11 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_date_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_stamp',
        ),
    ]
