# Generated by Django 3.0.5 on 2020-05-13 03:32

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_date_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=phone_field.models.PhoneField(default='09031144654', help_text='Contact phone number', max_length=31),
            preserve_default=False,
        ),
    ]
