# Generated by Django 3.0.5 on 2020-05-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200513_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='abandoned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='processing',
            field=models.BooleanField(default=True),
        ),
    ]
