# Generated by Django 3.0.5 on 2020-05-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200527_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_customer',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
