# Generated by Django 3.0.5 on 2020-06-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_profile_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_by_artisan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price_by_customer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
