# Generated by Django 2.2.2 on 2019-11-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_area_registeration_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='mobile',
            field=models.CharField(max_length=11),
        ),
    ]
