# Generated by Django 2.2.2 on 2019-11-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20191123_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLookUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('mobile', models.CharField(max_length=11)),
            ],
        ),
    ]
