# Generated by Django 2.2.2 on 2020-01-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_remove_feedback_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='efficiency',
            field=models.TextField(blank=True, null=True),
        ),
    ]
