# Generated by Django 3.0.5 on 2020-05-13 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_feedback_efficiency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registeration',
            new_name='Order',
        ),
    ]
