# Generated by Django 3.0.5 on 2020-05-13 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
