# Generated by Django 3.0.5 on 2020-05-14 12:05

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_auto_20200514_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=phone_field.models.PhoneField(help_text='Contact phone number', max_length=31),
        ),
    ]
